apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-demo-deployment
spec:
  selector:
    matchLabels:
      app: angular-demo-pod
  template:
    metadata:
      labels:
        app: angular-demo-pod
    spec:
      containers:
      - name: angular-demo-container
        image: contenedorregistrodesarrollo.azurecr.io/angular-demo:#{Build.BuildId}#
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: angular-demo-service
spec:
  selector:
    app: angular-demo-pod
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer